import type { Metadata } from "next";
import { Geist, Geist_Mono, Cinzel } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Credo Verum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Light-32.png" sizes="32x32" media="(prefers-color-scheme: light)" />
        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Dark-32.png" sizes="32x32" media="(prefers-color-scheme: dark)" />

        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Light-16.png" sizes="16x16" media="(prefers-color-scheme: light)" />
        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Dark-16.png" sizes="16x16" media="(prefers-color-scheme: dark)" />

        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Light-48.png" sizes="48x48" media="(prefers-color-scheme: light)" />
        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Dark-48.png" sizes="48x48" media="(prefers-color-scheme: dark)" />

        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Light-192.png" sizes="192x192" media="(prefers-color-scheme: light)" />
        <link rel="icon" href="/icons/Agnus-Dei-Favicon-Dark-192.png" sizes="192x192" media="(prefers-color-scheme: dark)" />

        <link rel="shortcut icon" href="/icons/Agnus-Dei-Favicon-Light-32.png" />

        <meta name="theme-color" content="#F3EEEA" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#776B5D" media="(prefers-color-scheme: dark)" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
